lecture-5-checkoutpage
IvanZenov/phoneshop-servlet-api pull request #6
Opened 2020-08-23 17:34 UTC by IvanZenov

2020-08-25 08:41 UTC, nd524s requested changes

2020-08-25 08:41 UTC, nd524s commented on src/main/java/com/es/phoneshop/dao/impl/OrderDaoImpl.java
> +                .orElseThrow(() -> new ProductNotFoundException("Order not found"));
Throw OrderNotFoundException here

2020-08-25 08:41 UTC, nd524s commented on src/main/java/com/es/phoneshop/model/entity/BaseEntity.java
> +public class BaseEntity implements Serializable {
Maybe you can do something like this in class declaration:
public class BaseEntity implements Serializable, Cloneable

You can avoid repetition of  "implements Serializable, Cloneable" in children classes

2020-08-25 08:41 UTC, nd524s commented on src/main/java/com/es/phoneshop/service/impl/OrderServiceImpl.java
> +                throw new RuntimeException();
Throw more specific RuntimeException with clear message what happened.

2020-08-25 08:41 UTC, nd524s commented on src/main/java/com/es/phoneshop/security/DosServiceImpl.java
> +    private static final long THRESHOLD = 10;
I think you need to add here a time condition as well. It's required by task

2020-08-25 18:29 UTC, IvanZenov commented on src/main/java/com/es/phoneshop/model/entity/BaseEntity.java
> +public class BaseEntity implements Serializable {
fix

2020-08-25 19:08 UTC, IvanZenov commented on src/main/java/com/es/phoneshop/security/DosServiceImpl.java
> +    private static final long THRESHOLD = 10;
fix

2020-08-25 19:10 UTC, IvanZenov commented on src/main/java/com/es/phoneshop/dao/impl/OrderDaoImpl.java
> +                .orElseThrow(() -> new ProductNotFoundException("Order not found"));
fix

2020-08-25 19:12 UTC, IvanZenov commented on src/main/java/com/es/phoneshop/service/impl/OrderServiceImpl.java
> +                throw new RuntimeException();
fix

2020-08-26 06:15 UTC, nd524s approved these changes

2020-08-26 06:15 UTC, merged